pipeline {
    agent any
    stages {
stage('scm') {
steps {
    git 'https://github.com/ganeshlovesdevops/maven_demo.git'
    }
}
    stage('build') {
    steps {
        withMaven(maven : 'mymaven'){
        bat "mvn clean install"
    }
    }
}

    stage('deploy') {
steps {
    bat 'copy "C:\Windows\System32\config\systemprofile\AppData\Local\Jenkins\.jenkins\workspace\raghuproject\\gameoflife-web\\target\\*.war" "C:\\Program Files\\Apache Software Foundation\\Tomcat 9.0\\webapps\\"'
    }
}
}
}
